-- ============================================================================
--  ConvertHub — database schema for `live_converter`
--  Generated by scripts/export-schema.js on 2026-10-02 — do not edit by hand,
--  edit src/db.js and run "npm run db:sql".
--
--  HOW TO USE (Navicat): connect to the live MySQL server → right-click the connection →
--  New Query → paste this file (or Query → Open) → Run (F5). Safe to run twice: every statement
--  is IF NOT EXISTS / CREATE OR REPLACE. Only the `live_converter` database is touched.
--
--  Then point the website at it:  DB_NAME=live_converter  (see deploy/.env.live.example)
-- ============================================================================

CREATE DATABASE IF NOT EXISTS `live_converter` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `live_converter`;

CREATE TABLE IF NOT EXISTS sessions (
    id CHAR(36) NOT NULL PRIMARY KEY,
    first_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    visits INT UNSIGNED NOT NULL DEFAULT 1,
    user_agent VARCHAR(512) NULL,
    device ENUM('desktop','mobile','tablet','bot','unknown') NOT NULL DEFAULT 'unknown',
    browser VARCHAR(64) NULL,
    os VARCHAR(64) NULL,
    ip_hash CHAR(64) NULL COMMENT 'SHA-256 of IP + salt (never the raw IP)',
    language VARCHAR(16) NULL,
    timezone VARCHAR(64) NULL,
    screen VARCHAR(16) NULL,
    theme VARCHAR(8) NULL,
    referrer VARCHAR(512) NULL,
    utm_source VARCHAR(128) NULL,
    utm_medium VARCHAR(128) NULL,
    utm_campaign VARCHAR(128) NULL,
    KEY idx_sessions_last_seen (last_seen),
    KEY idx_sessions_device (device)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Anonymous visitors (one row per browser)';

CREATE TABLE IF NOT EXISTS page_views (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id CHAR(36) NOT NULL,
    path VARCHAR(255) NOT NULL,
    tool_id VARCHAR(64) NULL,
    category VARCHAR(32) NULL,
    referrer VARCHAR(512) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_pv_session (session_id),
    KEY idx_pv_tool (tool_id),
    KEY idx_pv_created (created_at),
    CONSTRAINT fk_pv_session FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Every page opened';

CREATE TABLE IF NOT EXISTS conversions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    public_id CHAR(36) NOT NULL UNIQUE,
    session_id CHAR(36) NOT NULL,
    tool_id VARCHAR(64) NOT NULL,
    tool_title VARCHAR(128) NULL,
    category VARCHAR(32) NULL,
    engine VARCHAR(32) NULL,
    mode ENUM('each','all') NOT NULL DEFAULT 'each',
    location ENUM('browser','server','ai') NOT NULL DEFAULT 'browser' COMMENT 'where the work happened',
    status ENUM('started','success','error','cancelled') NOT NULL DEFAULT 'started',
    options_json JSON NULL,
    input_count INT UNSIGNED NOT NULL DEFAULT 0,
    input_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    output_count INT UNSIGNED NOT NULL DEFAULT 0,
    output_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    from_ext VARCHAR(16) NULL,
    to_ext VARCHAR(16) NULL,
    duration_ms INT UNSIGNED NULL,
    error_message VARCHAR(1000) NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at DATETIME NULL,
    KEY idx_conv_session (session_id),
    KEY idx_conv_tool (tool_id),
    KEY idx_conv_status (status),
    KEY idx_conv_started (started_at),
    KEY idx_conv_pair (from_ext, to_ext),
    CONSTRAINT fk_conv_session FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='One row per conversion job (browser, server or AI)';

CREATE TABLE IF NOT EXISTS files (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id CHAR(36) NOT NULL,
    conversion_id BIGINT UNSIGNED NULL,
    role ENUM('input','output') NOT NULL,
    name VARCHAR(512) NOT NULL,
    ext VARCHAR(16) NULL,
    mime VARCHAR(128) NULL,
    size_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    sha256 CHAR(64) NULL,
    width INT UNSIGNED NULL,
    height INT UNSIGNED NULL,
    pages INT UNSIGNED NULL,
    duration_sec DECIMAL(10,2) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    storage_path VARCHAR(512) NULL COMMENT 'relative path in the local archive folder (ARCHIVE_FILES=true)',
    drive_file_id VARCHAR(128) NULL COMMENT 'Google Drive file id once uploaded',
    drive_url VARCHAR(255) NULL,
    archived_at DATETIME NULL,
    KEY idx_files_session (session_id),
    KEY idx_files_conv (conversion_id),
    KEY idx_files_ext (ext),
    KEY idx_files_created (created_at),
    CONSTRAINT fk_files_session FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_files_conv FOREIGN KEY (conversion_id) REFERENCES conversions(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Metadata of every uploaded (input) and produced (output) file. Contents are never stored.';

CREATE TABLE IF NOT EXISTS downloads (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id CHAR(36) NOT NULL,
    conversion_id BIGINT UNSIGNED NULL,
    kind ENUM('single','zip','copy') NOT NULL DEFAULT 'single',
    file_name VARCHAR(512) NULL,
    size_bytes BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_dl_session (session_id),
    KEY idx_dl_conv (conversion_id),
    CONSTRAINT fk_dl_session FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_dl_conv FOREIGN KEY (conversion_id) REFERENCES conversions(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Download / copy-to-clipboard actions';

CREATE TABLE IF NOT EXISTS searches (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id CHAR(36) NOT NULL,
    query VARCHAR(255) NOT NULL,
    source ENUM('header','hero','palette','ai','smartdrop') NOT NULL DEFAULT 'header',
    results INT UNSIGNED NOT NULL DEFAULT 0,
    picked_tool VARCHAR(64) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_search_session (session_id),
    KEY idx_search_created (created_at),
    CONSTRAINT fk_search_session FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='What people search for (tells you which tools to build next)';

CREATE TABLE IF NOT EXISTS events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id CHAR(36) NOT NULL,
    name VARCHAR(64) NOT NULL,
    tool_id VARCHAR(64) NULL,
    props JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_ev_session (session_id),
    KEY idx_ev_name (name),
    KEY idx_ev_created (created_at),
    CONSTRAINT fk_ev_session FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Generic UI events (theme change, option change, share, palette open...)';

CREATE TABLE IF NOT EXISTS ai_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id CHAR(36) NULL,
    conversion_id BIGINT UNSIGNED NULL,
    feature VARCHAR(32) NOT NULL COMMENT 'find-tool | summarize | translate | keypoints | simplify | transcribe | custom',
    provider VARCHAR(32) NOT NULL DEFAULT 'ollama',
    model VARCHAR(64) NULL,
    input_chars INT UNSIGNED NULL,
    output_chars INT UNSIGNED NULL,
    input_bytes BIGINT UNSIGNED NULL,
    target_lang VARCHAR(32) NULL,
    duration_ms INT UNSIGNED NULL,
    status ENUM('success','error') NOT NULL DEFAULT 'success',
    error_message VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_ai_session (session_id),
    KEY idx_ai_feature (feature),
    KEY idx_ai_created (created_at),
    CONSTRAINT fk_ai_conv FOREIGN KEY (conversion_id) REFERENCES conversions(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Every call to the local AI (Ollama / Whisper)';

CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id CHAR(36) NULL,
    tool_id VARCHAR(64) NULL,
    conversion_id BIGINT UNSIGNED NULL,
    rating TINYINT UNSIGNED NULL COMMENT '1-5 stars',
    comment TEXT NULL,
    page VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_fb_tool (tool_id),
    KEY idx_fb_created (created_at),
    CONSTRAINT fk_fb_conv FOREIGN KEY (conversion_id) REFERENCES conversions(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Star ratings and comments from users';

CREATE TABLE IF NOT EXISTS error_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id CHAR(36) NULL,
    source ENUM('browser','server') NOT NULL,
    tool_id VARCHAR(64) NULL,
    message VARCHAR(2000) NOT NULL,
    stack TEXT NULL,
    url VARCHAR(512) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_err_created (created_at),
    KEY idx_err_tool (tool_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Errors from the browser and the server';

CREATE OR REPLACE VIEW v_daily_summary AS
    SELECT DATE(started_at) AS day,
           COUNT(*) AS conversions,
           SUM(status = 'success') AS successful,
           SUM(status = 'error') AS failed,
           COUNT(DISTINCT session_id) AS unique_users,
           SUM(input_count) AS files_in,
           ROUND(SUM(input_bytes) / 1048576, 2) AS input_mb,
           ROUND(SUM(output_bytes) / 1048576, 2) AS output_mb,
           ROUND(AVG(duration_ms) / 1000, 2) AS avg_seconds
    FROM conversions GROUP BY DATE(started_at) ORDER BY day DESC;

CREATE OR REPLACE VIEW v_tool_popularity AS
    SELECT tool_id, MAX(tool_title) AS tool_title, MAX(category) AS category,
           COUNT(*) AS runs, SUM(status = 'success') AS successful, SUM(status = 'error') AS failed,
           ROUND(100 * SUM(status = 'success') / COUNT(*), 1) AS success_rate_pct,
           COUNT(DISTINCT session_id) AS unique_users,
           ROUND(SUM(input_bytes) / 1048576, 2) AS input_mb,
           ROUND(AVG(duration_ms) / 1000, 2) AS avg_seconds,
           MAX(started_at) AS last_used
    FROM conversions GROUP BY tool_id ORDER BY runs DESC;

CREATE OR REPLACE VIEW v_format_pairs AS
    SELECT from_ext, to_ext, COUNT(*) AS runs, SUM(status = 'success') AS successful,
           ROUND(SUM(input_bytes) / 1048576, 2) AS input_mb
    FROM conversions WHERE from_ext IS NOT NULL GROUP BY from_ext, to_ext ORDER BY runs DESC;

CREATE OR REPLACE VIEW v_hourly_activity AS
    SELECT HOUR(started_at) AS hour_of_day, COUNT(*) AS conversions
    FROM conversions GROUP BY HOUR(started_at) ORDER BY hour_of_day;

CREATE OR REPLACE VIEW v_recent_activity AS
    SELECT c.id, c.public_id, c.started_at, c.tool_title, c.status, c.location,
           c.input_count, ROUND(c.input_bytes / 1024, 1) AS input_kb, c.from_ext, c.to_ext,
           ROUND(c.duration_ms / 1000, 2) AS seconds, c.error_message, s.device, s.browser, s.os
    FROM conversions c JOIN sessions s ON s.id = c.session_id
    ORDER BY c.started_at DESC;

CREATE OR REPLACE VIEW v_missing_tools AS
    SELECT query, COUNT(*) AS times_searched, MAX(created_at) AS last_searched
    FROM searches WHERE results = 0 GROUP BY query ORDER BY times_searched DESC;

-- ----------------------------------------------------------------------------
--  OPTIONAL — a dedicated login for the website with rights on this database only.
--  Change the password first! Needs CREATE USER privilege (ask your DBA / use root);
--  if you get "Access denied", skip this block and let the website use your existing login.
-- ----------------------------------------------------------------------------
-- CREATE USER IF NOT EXISTS 'converthub_app'@'%' IDENTIFIED BY 'CHANGE_ME_strong_password';
-- GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES, CREATE VIEW, SHOW VIEW ON `live_converter`.* TO 'converthub_app'@'%';
-- FLUSH PRIVILEGES;
