// Writes deploy/live_converter.sql — the complete ConvertHub schema as plain SQL, generated from the
// same definitions the server uses (src/db.js). Open the file in Navicat (Query → Open → Run) to create
// the `live_converter` database on any MySQL 8 server without starting the website.
// Run after changing SCHEMA:  npm run db:sql   [--db other_name]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const argDb = process.argv.indexOf('--db');
const dbName = argDb > -1 ? process.argv[argDb + 1] : 'live_converter';
if (!/^[A-Za-z0-9_]+$/.test(dbName)) { console.error('Database name may contain letters, digits and _ only'); process.exit(1); }

process.env.DB_ENABLED = 'false'; // importing db.js must not try to connect
const { SCHEMA } = await import('../src/db.js');

const banner = `-- ============================================================================
--  ConvertHub — database schema for \`${dbName}\`
--  Generated by scripts/export-schema.js on ${new Date().toISOString().slice(0, 10)} — do not edit by hand,
--  edit src/db.js and run "npm run db:sql".
--
--  HOW TO USE (Navicat): connect to the live MySQL server → right-click the connection →
--  New Query → paste this file (or Query → Open) → Run (F5). Safe to run twice: every statement
--  is IF NOT EXISTS / CREATE OR REPLACE. Only the \`${dbName}\` database is touched.
--
--  Then point the website at it:  DB_NAME=${dbName}  (see deploy/.env.live.example)
-- ============================================================================

CREATE DATABASE IF NOT EXISTS \`${dbName}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE \`${dbName}\`;

`;

const body = SCHEMA.map(s => s.trim().replace(/\s+$/, '') + ';').join('\n\n');

const userBlock = `

-- ----------------------------------------------------------------------------
--  OPTIONAL — a dedicated login for the website with rights on this database only.
--  Change the password first! Needs CREATE USER privilege (ask your DBA / use root);
--  if you get "Access denied", skip this block and let the website use your existing login.
-- ----------------------------------------------------------------------------
-- CREATE USER IF NOT EXISTS 'converthub_app'@'%' IDENTIFIED BY 'CHANGE_ME_strong_password';
-- GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES, CREATE VIEW, SHOW VIEW ON \`${dbName}\`.* TO 'converthub_app'@'%';
-- FLUSH PRIVILEGES;
`;

const out = path.join(root, 'deploy', `${dbName}.sql`);
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, banner + body + userBlock);
console.log(`wrote ${path.relative(root, out)} (${SCHEMA.length} objects)`);
